#! /bin/sh
### BEGIN INIT INFO
# Provides:          website_updater
# Required-Start:    $all
# Required-Stop:    $all
# Default-Start:    2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts website_updater
# Description:      Starts website_updater using hypnotoad
### END INIT INFO
 
WU_HOME=/nfs/public/rw/reseq-info/static_website_updater/gca_website_updater
SCRIPT=$WU_HOME/scripts/website_updater/website_updater.pl

test -d $WU_HOME || exit 0

if [[ ! $PATH =~ (^|:)$WU_HOME/local/bin(:|$) ]]; then
    PATH=$PATH:$WU_HOME/local/bin
fi
 
set -e
 
case "$1" in
  start)
    echo "Starting $SCRIPT"
    cd $WU_HOME
    carton exec hypnotoad $SCRIPT
    ;;
  stop)
    echo "Stopping $SCRIPT"
    carton exec hypnotoad --stop $SCRIPT
    ;;
  install)
    echo "installing modules for $SCRIPT"
    cd $WU_HOME
    mkdir -p $WU_HOME/local/
    cpanm -L local git@github.com:Ensembl/ensembl-git-tools.git \
    && carton install --deployment \
    && curl https://codeload.github.com/git/git/tar.gz/v2.5.0 >git.tar.gz \
    && tar -xzf git.tar.gz \
    && cd git-2.5.0/ \
    &&  make prefix=$WU_HOME/local/ \
    &&  make prefix=$WU_HOME/local/ install
    rm -fr $WU_HOME/git.tar.gz $WU_HOME/git-2.5.0
    ;;
  restart|force-reload)
    ${0} stop
    sleep 0.5
    ${0} start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac
 
exit 0
